#1. an R function named myunif that accepts three parameters: n,
#the number of variates to generate; a, the lower limit of the distribution; 
#and b, the upper limit of the distribution.Your function must return a vector
#of n uniform (a, b) random variates. Each variate must be generated by 
#inverting a single call to runif(1) - use the idf determined by setting
#u = F(x) and solving for x 
#uniform random variates
myunif = function(n,a,b){
  u <- runif(seq(n))
  x <- u*(b-a)+a
  hist(x, freq=FALSE)
  abline(h=dunif(x,a,b))
  return (x)
}
#first sample
myunif1 = myunif(1000,10,20)

mean(myunif1)
sd(myunif1)


#theoretical value
a= 10
b=20
meanval <- (a+b)/2
meanval
sigma <- (b-a)/sqrt(12)
sigma
        
#2 triangular random variates
mytriang <- function(n,a,b,c){
  u <- runif(seq(n))
  x <- c()
  for (i in u){
    if(0<i && i <((c-a)/(b-a))){
      x<- append(x,a+sqrt((i)*(b-a)*(c-a)))
    } else if (((c-a)/(b-a))<=i && i<1){
      x<-append(x,b-sqrt((1-i)*(b-a)*(b-c)))
    }

  }
  hist(x,freq=FALSE)
  segments(a,0,c,2/(b-a))
  segments(c,2/(b-a),b,0)
  return (x)
}
      
a <- 10
b <- 25
c <- 15
n <- 10000

#first sample
triangle <- mytriang(n,a,b,c)
mean(triangle)
sd(triangle)

#theoretical value

meanval <- (a+b+c)/3
meanval
sigma <- sqrt((1/18)*(a^2+b^2+c^2-a*b-a*c-b*c))
sigma


